version: '2'
services:
  rabbitmq:
    image: 192.168.99.100:5000/rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: amqp

  zipkin:
    image: 192.168.99.100:5000/zipkin
    container_name: zipkin
    hostname: zipkin
    depends_on:
      - rabbitmq
    ports:
      - "9411:9411"
    environment:
      RABBIT_ADDRESSES: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASSWORD: amqp

  config-server:
    image: 192.168.99.100:5000/config-server
    container_name: config-server
    hostname: config-server
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8888:8888"
    volumes:
      - $APP_CONFIG_DIR:/etc/msdemo
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      APP_CONFIG_DIR: /etc/msdemo
      APP_LOGGING_DIR: /var/log/msdemo
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka/
      RABBITMQ_SERVICE_HOST: rabbitmq
      RABBITMQ_SERVICE_PORT: 5672
      RABBITMQ_SERVICE_USERNAME: admin
      RABBITMQ_SERVICE_PASSWORD: amqp

  service-registry:
    image: 192.168.99.100:5000/service-registry
    container_name: service-registry
    hostname: service-registry
    restart: always
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888

  turbine-server:
    image: 192.168.99.100:5000/turbine-server
    container_name: turbine-server
    hostname: turbine-server
    restart: always
    depends_on:
      - service-registry
    ports:
      - "8989:8989"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888

  monitor-dashboard:
    image: 192.168.99.100:5000/monitor-dashboard
    container_name: monitor-dashboard
    hostname: monitor-dashboard
    restart: always
    depends_on:
      - service-registry
      - turbine-server
    ports:
      - "7979:7979"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888

  auth-service:
    image: 192.168.99.100:5000/auth-service
    container_name: auth-service
    hostname: auth-service
    restart: always
    depends_on:
      - service-registry
    ports:
      - "9000:9000"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888

  account-service:
    image: 192.168.99.100:5000/account-service
    container_name: account-service
    hostname: account-service
    restart: always
    depends_on:
      - service-registry
    ports:
      - "9010:9010"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888

  api-gateway:
    image: 192.168.99.100:5000/cloud-gateway
    container_name: cloud-gateway
    hostname: cloud-gateway
    restart: always
    depends_on:
      - service-registry
    ports:
      - "8080:8080"
    volumes:
      - $APP_LOGGING_DIR:/var/log/msdemo
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
