logging:
  file: ${APP_LOGGING_DIR}/${spring.application.name}.log
  level:
    demo: DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL}

# integrate rabbitmq for turbine stream and push refresh config
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: amqp
  sleuth:
    sampler:
      # recording all spans for demo
      percentage: 1.0

### not supported in Camden.SR4
#management.security.enabled: false
#endpoints:
#  restart.enabled: true
#  shutdown.enabled: true
