apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
  labels:
    volume-name: config-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /Users/yenchu/git/microservices-demo/config-server/src/main/resources/shared
