apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    volume-name: db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/yenchu/data/mysql