apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  labels:
    volume-name: log-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/yenchu/log/microservices-demo
