APP_CONFIG_DIR: /Users/yenchu/git/microservices-demo/config-server/src/main/resources/shared
APP_LOGGING_DIR: /Users/yenchu/log/microservices-demo
SERVICE_REGISTRY_URL: http://127.0.0.1:8761/eureka/

RABBITMQ_SERVICE_HOST: localhost
RABBITMQ_SERVICE_PORT: 5672
RABBITMQ_SERVICE_USERNAME: admin
RABBITMQ_SERVICE_PASSWORD: amqp

logging:
  file: ${APP_LOGGING_DIR}/${spring.application.name}.log
  level:
    demo: DEBUG

spring:
  rabbitmq:
    host: ${RABBITMQ_SERVICE_HOST}
    port: ${RABBITMQ_SERVICE_PORT}
    username: ${RABBITMQ_SERVICE_USERNAME}
    password: ${RABBITMQ_SERVICE_PASSWORD}
  cloud:
    config:
      server:
        native:
          search-locations: file:${APP_CONFIG_DIR}
        overrides:
          SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
          APP_LOGGING_DIR: ${APP_LOGGING_DIR}
          spring.rabbitmq.host: ${RABBITMQ_SERVICE_HOST}
          spring.rabbitmq.port: ${RABBITMQ_SERVICE_PORT}
          spring.rabbitmq.username: ${RABBITMQ_SERVICE_USERNAME}
          spring.rabbitmq.password: ${RABBITMQ_SERVICE_PASSWORD}
  profiles:
    active: native

### not supported in Camden.SR4
#management.security.enabled: false
#endpoints:
#  restart.enabled: true
#  shutdown.enabled: true
