APP_CONFIG_DIR: /Users/yenchu/workspace/ms-demo/config-server/src/main/resources/shared
APP_LOGGINH_DIR: /Users/yenchu/workspace/log
SERVICE_REGISTRY_URL: http://127.0.0.1:8761/eureka/
RABBITMQ_HOST: localhost

logging:
  file: ${APP_LOGGINH_DIR}/${spring.application.name}.log
  level:
    demo: DEBUG

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: admin
    password: amqp
  cloud:
    config:
      server:
        native:
          search-locations: file:${APP_CONFIG_DIR}
        overrides:
          SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
          APP_LOGGINH_DIR: ${APP_LOGGINH_DIR}
          spring.rabbitmq.host: ${spring.rabbitmq.host}
          spring.rabbitmq.port: ${spring.rabbitmq.port}
          spring.rabbitmq.username: ${spring.rabbitmq.username}
          spring.rabbitmq.password: ${spring.rabbitmq.password}
  profiles:
    active: native
